name: e2e-tests-playwright-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - E2E/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: "22.x"

steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    displayName: Use Node.js $(nodeVersion)
    inputs:
      versionSpec: $(nodeVersion)

  - script: |
      npm ci
    displayName: Install E2E dependencies
    workingDirectory: E2E

  - script: |
      npx playwright install --with-deps
    displayName: Install Playwright browsers
    workingDirectory: E2E

  - script: |
      npx playwright test
    displayName: Run E2E tests with Playwright
    workingDirectory: E2E

  - task: PublishPipelineArtifact@1
    displayName: Publish Playwright test results
    condition: always()
    inputs:
      targetPath: E2E/test-results
      artifact: e2e-playwright-test-results
      publishLocation: pipeline
