name: e2e-tests-allure-testops

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: E2E
        run: npm ci

      - name: Install Playwright browsers
        working-directory: E2E
        run: npx playwright install --with-deps

      - name: Run tests and upload to TestOps
        working-directory: E2E
        env:
          CI: "true"
          TESTOPS_URL: ${{ secrets.TESTOPS_URL }}
          TESTOPS_TOKEN: ${{ secrets.TESTOPS_TOKEN }}
          TESTOPS_PROJECT_ID: ${{ secrets.TESTOPS_PROJECT_ID }}
        run: npx allure run --config ./allurerc.testops.mjs -- npx playwright test
